# Generated by Django 4.2.3 on 2023-09-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_is_special'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter_price',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(choices=[('৳0 - ৳100', '৳0 - ৳100'), ('৳100 - ৳200', '৳100 - ৳200'),
                 ('৳200 - ৳500', '৳200 - ৳500'), ('৳500 - ৳1000', '৳500 - ৳1000')], max_length=60)),
            ],
        ),
    ]
