# Generated by Django 4.2.3 on 2023-09-02 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_filter_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Filter_price',
        ),
    ]
